export const drivers = [
  { id: 1, name: "Lewis Hamilton", team: "Mercedes" },
  { id: 2, name: "Valtteri Bottas", team: "Mercedes" },
  { id: 3, name: "Max Verstappen", team: "Red Bull" },
  { id: 4, name: "Sergio Pérez", team: "Red Bull" },
  { id: 5, name: "Charles Leclerc", team: "Ferrari" },
  { id: 6, name: "Carlos Sainz", team: "Ferrari" },
  { id: 7, name: "Lando Norris", team: "McLaren" },
  { id: 8, name: "Daniel Ricciardo", team: "McLaren" },
  { id: 9, name: "Pierre Gasly", team: "Alpine" },
  { id: 10, name: "Yuki Tsunoda", team: "AlphaTauri" },
  { id: 11, name: "Fernando Alonso", team: "Alpine" },
  { id: 12, name: "Esteban Ocon", team: "AlphaTauri" },
  { id: 13, name: "Lance Stroll", team: "Aston Martin" },
  { id: 14, name: "Mick Schumacher", team: "Haas" },
  { id: 15, name: "Sebastian Vettel", team: "Aston Martin" },
  { id: 16, name: "Kimi Räikkönen", team: "Alfa Romeo" },
  { id: 17, name: "Antonio Giovinazzi", team: "Alfa Romeo" },
  { id: 18, name: "Romain Grosjean", team: "Williams" },
  { id: 19, name: "Kevin Magnussen", team: "Haas" },
  { id: 20, name: "George Russell", team: "Williams" },
  { id: 21, name: "Nicholas Latifi", team: "Williams" },
  { id: 22, name: "George Russell", team: "Williams" },
  { id: 23, name: "Sergio Pérez", team: "Red Bull" },
  { id: 24, name: "Fernando Alonso", team: "Alpine" },
  { id: 25, name: "Carlos Sainz", team: "Ferrari" },
  { id: 26, name: "Lando Norris", team: "McLaren" },
  { id: 27, name: "Charles Leclerc", team: "Ferrari" },
  { id: 28, name: "Max Verstappen", team: "Red Bull" },
  { id: 29, name: "Valtteri Bottas", team: "Mercedes" },
  { id: 30, name: "Lewis Hamilton", team: "Mercedes" },
];
